### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by woodbri** [farmOS/farm_grazing#2]
### Track various item on a TODO list:
- [x] add rotation logs to Herds/Rotations page
- [x] add support for actual items that are fixed and planned items that are changeable
- [x] disable changes to Herds/Rotation drag and drop to disable rows that are done
- ----
- [x] setup config form for defining animal types and import/exporting them. I think Mike had this on his list farm_grazing.module has 'farm/grazing/config/animal_types' menu path defined and function is in farm_grazing.pages.inc
- ----
- [x] Add shortcuts to Implement page, more might be needed in phase 3
- ----
- [x] implement non-growing season
- ----
- [x] when creating a herd, verify that all components of the herd are in or moved to the same paddock
- [x] Update farm_grazing_validate_herd() based on your latest code
- [x] fix farm_grazing.herds.manage.inc farm_grazing_validate_herd()
- ----
- [x] warn user when changes to paddock count, quality, or recovery times that this will impact rotations
- [x] implement farm_group_get_members($obj) in farm_grazing.utils.inc
- [x] grep for href and src= in src and fix absolute urls

### Phase three stuff:

See Ticket #3

**Comment by woodbri** [comment]
Completed Phase 2 work. Closing.

**Comment by mstenta** [comment]
Woo hoo!
